import type { Locale } from "../schemas/locale";

// Rotating home hero subtitle pool — one line per locale, independently
// indexed (arrays don't need matching lengths or matching themes at the same
// index). Pure content, no ids, so nothing else references an entry by
// position.
export const islamicHeroTextsAr = [
  "✨ نور لرحلتك اليومية",
  "🌿 زادٌ للقلب والروح",
  "🌅 ابدأ يومك بذكر الله",
  "📖 مع القرآن حياة",
  "🕌 رحلة إيمانية كل يوم",
  "🤲 طريقك إلى الطمأنينة",
  "💙 لحظات تقربك إلى الله",
  "📜 نور القرآن بين يديك",
  "🤍 ذكرٌ يحيي القلب",
  "🌞 خير البداية مع الله",
  "🌸 اجعل يومك عامرًا بالطاعة",
  "🕊️ خطوة نحو الجنة",
  "💫 أنر قلبك بالإيمان",
  "🤝 رفيقك في الخير",
  "🌱 كل يوم فرصة للطاعة",
  "🎧 استمع وتدبر",
  "📚 عيش مع القرآن",
  "🌍 إيمان يرافقك أينما كنت",
  "✨ نور وهداية",
  "🌙 رحلة إلى السكينة",
  "🤲 في ذكر الله راحة",
  "🌾 خير الزاد التقوى",
  "📖 تدبر آيات الله",
  "❤️ قلبٌ مطمئن بذكر الله",
  "📘 اجعل القرآن رفيقك",
  "🌬️ أنفاسٌ من الإيمان",
  "⏳ كل لحظة عبادة",
  "🤲 معًا نحو رضوان الله",
  "🚶 طريق الخير يبدأ هنا",
  "💡 نورٌ يملأ حياتك",
  "📈 استزد من الخير",
  "🕌 بابك إلى المعرفة الإسلامية",
  "📖 اقرأ، استمع، وتدبر",
  "🤲 أذكارك بين يديك",
  "🌟 خير الأعمال أدومها",
  "⏰ اغتنم كل لحظة",
  "💓 نبض الإيمان",
  "📜 مع السنة حياة",
  "📖 اقترب من القرآن",
  "💫 هداية لكل قلب",
  "🤍 ذكرٌ يرافق يومك",
  "🕊️ سلامٌ للقلب",
  "🌺 أثرٌ يبقى",
  "✨ طريق النور",
  "🤲 كن أقرب إلى الله",
  "🌄 ابدأ بخير",
  "💚 الإيمان أسلوب حياة",
  "🤝 معًا في طريق الطاعة",
  "🌙 لحظات من السكينة",
  "🪴 ارتقِ بروحك",
  "🌞 خيرٌ يتجدد كل يوم",
  "📅 اقرأ آية اليوم",
  "🎙️ استمع إلى القرآن",
  "🎓 تعلم دينك بسهولة",
  "🤲 اجعل الذكر عادة",
  "🤍 نحو قلبٍ أنقى",
  "📚 رحلة العلم والإيمان",
  "💌 رسائل إيمانية يومية",
  "✨ نور على نور",
  "⏳ اجعل وقتك عبادة",
  "🌌 تأمل في آيات الله",
  "💖 القرآن شفاء ورحمة",
  "📜 سنةٌ تهديك",
  "🎁 خيرٌ ينتظرك",
  "🤲 مع الله تطمئن القلوب",
  "🕰️ عبادة في كل وقت",
  "🤍 كن من الذاكرين",
  "📖 صفحة جديدة مع الله",
  "🌅 حياةٌ بنور القرآن",
  "💙 لحظة قرب",
  "📚 تلاوة، تدبر، عمل",
  "🌿 اجعل الخير رفيقك",
  "📜 خير الكلام كلام الله",
  "✨ نور الإيمان",
  "❤️ اجعل قلبك حيًا",
  "📖 مع كل آية هداية",
  "⏳ استثمر وقتك في الطاعة",
  "🌸 كل يوم خير",
  "🎒 زاد المؤمن",
  "🤍 من القلب إلى الجنة",
  "😊 طريق السعادة يبدأ بالإيمان",
  "💫 خيرٌ يلامس روحك",
  "🕊️ سكينة في كل لحظة",
  "✨ نورٌ لا ينطفئ",
  "☪️ الإسلام حياة",
  "📚 تدبر، تعلم، اعمل",
  "📖 على هدي القرآن",
  "🌺 مع الذكر يزهر القلب",
  "🤲 أقرب إلى الله كل يوم",
  "🚶 خيرٌ يرافق رحلتك",
  "🌞 أشرق بالإيمان",
  "👣 ابدأ بخطوة خير",
  "🌿 نحو حياة مباركة",
  "💚 إيمان يتجدد",
  "🕌 هداية بين يديك",
  "📖 مع القرآن تطمئن النفوس",
  "🌸 خيرٌ لكل يوم",
  "✨ نورٌ يقودك",
  "🤲 اجعل يومك أقرب إلى الله",
  "🚀 طريقك إلى الخير يبدأ الآن",
  "🌙 كل فجر بداية جديدة",
  "🌸 ازرع الخير في كل يوم",
  "🤲 الدعاء مفتاح الفرج",
  "📿 سبّح بحمد ربك",
  "💙 السكينة تبدأ من القلب",
  "🕋 اجعل قبلتك رضا الله",
  "📖 آية تغيّر يومك",
  "🌿 استقم تجد الخير",
  "☁️ توكل على الله دائمًا",
  "🤍 الإخلاص سر القبول",
  "🕊️ طهّر قلبك بالمحبة",
  "🌧️ رحمة الله واسعة",
  "🌟 ابتسم واحتسب الأجر",
  "💡 اهتدِ بنور الوحي",
  "🌺 ازدد قربًا من الرحمن",
  "🕌 بيت الله ينتظرك",
  "🤲 استعن بالله ولا تعجز",
  "📚 تعلّم شيئًا من دينك اليوم",
  "🌙 اجعل الليل شاهدًا لك",
  "✨ الخير عادة المؤمن",
  "🧭 وجهتك إلى الجنة",
  "🌼 كن سببًا في الخير",
  "❤️ المحبة في الله نعمة",
  "📖 القرآن ربيع القلوب",
  "🌱 ازرع حسناتٍ لا تنقطع",
  "🤲 باب التوبة مفتوح",
  "🌄 صباحٌ بطاعة وبركة",
  "🌃 مساءٌ مليء بالأذكار",
  "🕊️ اغفر ليومك يصفُ قلبك",
  "💖 برّ الوالدين طريق الجنة",
  "🌸 الكلمة الطيبة صدقة",
  "🤝 ساعد غيرك تؤجر",
  "🌍 كن رحمةً لمن حولك",
  "💫 النية الصالحة تصنع الفرق",
  "📿 لا تنسَ وردك اليومي",
  "🌺 اجعل قلبك موطنًا للسلام",
  "🕌 كل صلاة نور",
  "🤍 املأ وقتك بما ينفع",
  "📖 اقرأ ولو آية",
  "🌿 استغفر بقلب حاضر",
  "✨ كل ذكرٍ نور",
  "🌞 أنر صباحك بالإيمان",
  "🌙 اختم يومك بالطاعة",
  "🎁 الخير يعود إلى صاحبه",
  "🪴 اغرس أثرًا طيبًا",
  "🤲 ما خاب من دعا الله",
  "📚 المعرفة تقود إلى العمل",
  "💚 القرب من الله أجمل نعمة",
  "💫 الأمل بالله لا يخيب",
  "🕊️ سلامٌ يملأ روحك",
] as const;

export const islamicHeroTextsEn = [
  "✨ Light for your daily journey",
  "🌿 Nourishment for your heart and soul",
  "🌅 Begin your day with the remembrance of Allah",
  "📖 Life with the Qur'an",
  "🕌 A daily journey of faith",
  "🤲 Your path to tranquility",
  "💙 Moments that bring you closer to Allah",
  "📜 The light of the Qur'an at your fingertips",
  "🤍 Remembrance revives the heart",
  "🌞 The best beginning is with Allah",
  "🌸 Fill your day with worship",
  "🕊️ A step toward Paradise",
  "💫 Illuminate your heart with faith",
  "🤝 Your companion in goodness",
  "🌱 Every day is a new opportunity for worship",
  "🎧 Listen and reflect",
  "📚 Live with the Qur'an",
  "🌍 Faith accompanies you wherever you are",
  "✨ Light and guidance",
  "🌙 A journey to serenity",
  "🤲 In Allah's remembrance lies peace",
  "🌾 The best provision is piety",
  "📖 Reflect upon Allah's verses",
  "❤️ A heart at peace through Allah's remembrance",
  "📘 Make the Qur'an your companion",
  "🌬️ A breath of faith",
  "⏳ Every moment is an act of worship",
  "🤲 Together toward Allah's pleasure",
  "🚶 The path of goodness starts here",
  "💡 Light that fills your life",
  "📈 Grow in goodness every day",
  "🕌 Your gateway to Islamic knowledge",
  "📖 Read, listen, and reflect",
  "🤲 Your daily adhkar at your fingertips",
  "🌟 The best deeds are those done consistently",
  "⏰ Make every moment count",
  "💓 The heartbeat of faith",
  "📜 Life with the Sunnah",
  "📖 Draw closer to the Qur'an",
  "💫 Guidance for every heart",
  "🤍 Remembrance throughout your day",
  "🕊️ Peace for the heart",
  "🌺 A lasting impact",
  "✨ The path of light",
  "🤲 Draw closer to Allah",
  "🌄 Start with goodness",
  "💚 Faith is a way of life",
  "🤝 Together on the path of worship",
  "🌙 Moments of serenity",
  "🪴 Elevate your soul",
  "🌞 Renewed goodness every day",
  "📅 Read today's verse",
  "🎙️ Listen to the Qur'an",
  "🎓 Learn your religion with ease",
  "🤲 Make remembrance a daily habit",
  "🤍 Toward a purer heart",
  "📚 A journey of knowledge and faith",
  "💌 Daily messages of faith",
  "✨ Light upon light",
  "⏳ Turn your time into worship",
  "🌌 Reflect on Allah's signs",
  "💖 The Qur'an is healing and mercy",
  "📜 The Sunnah guides you",
  "🎁 Goodness awaits you",
  "🤲 With Allah, hearts find peace",
  "🕰️ Worship at every moment",
  "🤍 Be among those who remember Allah",
  "📖 A new page with Allah",
  "🌅 A life illuminated by the Qur'an",
  "💙 A moment of closeness",
  "📚 Recite, reflect, and act",
  "🌿 Let goodness be your companion",
  "📜 The best speech is the Word of Allah",
  "✨ The light of faith",
  "❤️ Keep your heart alive",
  "📖 Every verse is guidance",
  "⏳ Invest your time in worship",
  "🌸 Every day brings goodness",
  "🎒 The believer's provision",
  "🤍 From the heart to Paradise",
  "😊 The path to happiness begins with faith",
  "💫 Goodness that touches your soul",
  "🕊️ Serenity in every moment",
  "✨ A light that never fades",
  "☪️ Islam is a way of life",
  "📚 Reflect, learn, and act",
  "📖 Guided by the Qur'an",
  "🌺 Hearts bloom with remembrance",
  "🤲 Closer to Allah every day",
  "🚶 Goodness accompanies your journey",
  "🌞 Shine with faith",
  "👣 Take your first step toward goodness",
  "🌿 Toward a blessed life",
  "💚 Faith renewed",
  "🕌 Guidance at your fingertips",
  "📖 With the Qur'an, hearts find peace",
  "🌸 Goodness every day",
  "✨ Light leading your way",
  "🤲 Make today closer to Allah",
  "🚀 Your journey to goodness starts now",
  "🌙 Every dawn is a new beginning",
  "🌸 Plant goodness every day",
  "🤲 Supplication is the key to relief",
  "📿 Glorify your Lord",
  "💙 Peace begins within the heart",
  "🕋 Make Allah's pleasure your direction",
  "📖 One verse can change your day",
  "🌿 Stay steadfast and find goodness",
  "☁️ Put your trust in Allah",
  "🤍 Sincerity is the key to acceptance",
  "🕊️ Purify your heart with love",
  "🌧️ Allah's mercy is vast",
  "🌟 Smile and seek the reward",
  "💡 Be guided by divine light",
  "🌺 Draw closer to the Most Merciful",
  "🕌 Allah's House awaits you",
  "🤲 Seek Allah's help and never give up",
  "📚 Learn something new about your faith today",
  "🌙 Let the night bear witness for you",
  "✨ Goodness is the believer's habit",
  "🧭 Your destination is Paradise",
  "🌼 Be a source of goodness",
  "❤️ Love for Allah's sake is a blessing",
  "📖 The Qur'an is the spring of hearts",
  "🌱 Plant lasting good deeds",
  "🤲 The door of repentance is always open",
  "🌄 A morning filled with worship and blessings",
  "🌃 An evening filled with remembrance",
  "🕊️ Forgive, and let your heart find peace",
  "💖 Honoring your parents leads to Paradise",
  "🌸 A kind word is charity",
  "🤝 Help others and earn reward",
  "🌍 Be a mercy to those around you",
  "💫 A sincere intention makes all the difference",
  "📿 Don't forget your daily remembrance",
  "🌺 Make your heart a home for peace",
  "🕌 Every prayer is light",
  "🤍 Fill your time with what benefits you",
  "📖 Read even a single verse",
  "🌿 Seek forgiveness with a sincere heart",
  "✨ Every remembrance is light",
  "🌞 Brighten your morning with faith",
  "🌙 End your day with worship",
  "🎁 Goodness always returns to its giver",
  "🪴 Plant a lasting legacy",
  "🤲 Whoever calls upon Allah is never disappointed",
  "📚 Knowledge leads to action",
  "💚 Nearness to Allah is the greatest blessing",
  "💫 Hope in Allah never disappoints",
  "🕊️ Peace that fills your soul",
] as const;

function dayOfYear(date: Date): number {
  const start = Date.UTC(date.getFullYear(), 0, 0);
  const current = Date.UTC(date.getFullYear(), date.getMonth(), date.getDate());
  return Math.floor((current - start) / 86_400_000);
}

// Deterministic pick by day-of-year so every visitor on a given locale sees
// the same hero line all day, rotating at local midnight — same rationale as
// pickDhikrOfTheDay. Callers should pass a client-local `date` (defaults to
// `new Date()`); unlike pickDhikrOfTheDay this has no progress-reset boundary
// to stay in sync with, so calling it from a server component is fine too.
export function pickHeroTextOfTheDay(locale: Locale, date: Date = new Date()): string {
  const pool = locale === "ar" ? islamicHeroTextsAr : islamicHeroTextsEn;
  const index = dayOfYear(date) % pool.length;
  return pool[index] ?? pool[0];
}
